name: Copy MkDocs Files

on:
  push:
    branches:
      - main

jobs:
  copy_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy MkDocs Files
        run: cp -R D:\Drive\Anthony\Documents\Ambre/* .

